### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Betrisa** [zecoxao/zecoxao.github.io#1]
thank you for share.
i have downloaded the zip file and extracted on my webhost and it is not work , onlye sucks on loading.
link -> http://betrisagame.ir/505

**Comment by zecoxao** [comment]
yeah, i'm trying to fix right now. it's really weird since it's the exact same files as celeste's page

**Comment by Betrisa** [comment]
Thank you for fast reply.
yep , it is fixed now and works fine.
Regards.

is there any way to build fake PKGs from original games data downloaded via PSN ?
i have a full archive of games data extracted with PSX Download Helper.
![capture](https://user-images.githubusercontent.com/40128384/41201129-631a8d5e-6cc7-11e8-8704-d9fe5392665d.PNG)

**Comment by zecoxao** [comment]
there isn't sorry, psn packages require license activation.
closing...

**Comment by Betrisa** [comment]
why sometimes PS4 will turn off after 2-3 hours playing like overheat issue ?
is that normal ?
i use your Cache jailbreak .
Regards

**Comment by zecoxao** [comment]
happens also with mira+hen, which is what this page uses. nothing i can do about it

**Comment by Betrisa** [comment]
i want just run my games ! which one i have to use ? mira or hen ?

**Comment by zecoxao** [comment]
you can just use xvortex hen if you have issues with this page :)
